% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Case Study},
  pdfauthor={Bhavikkumar Mistry},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Case Study}
\author{Bhavikkumar Mistry}
\date{2024-06-12}

\begin{document}
\maketitle

\emph{About a company} Bellabeat, a high-tech manufacturer of
health-focused products for women. Bellabeat is a successful small
company, but they have the potential to become a larger player in the
global smart device market. Urška Sršen, cofounder and Chief Creative
Officer of Bellabeat, believes that analyzing smart device fitness data
could help unlock new growth opportunities for the company.

\emph{Ask} \textbf{Questions for Analysis} -What are some trends in
smart device usage? -How could these trends apply to Bellabeat
customers? -How could these trends help influence Bellabeat marketing
strategy

\emph{Prepare} \textbf{Dataset}

The dataset used in this analysis was obtained from Fitbit Fitness
Trackers and accessed through Kaggle public domain FitBit Dataset (CC0).
The data was collected from thirty-three eligible Fitbit users who
consented to the submission of personal tracker data, including
minute-level output for physical activity, heart rate, and sleep through
Amazon Mechanical Turk between April 12, 2016 and May 12, 2016. The
dataset is updated annually with the most recent being on March 2nd,
2024. The data consists of 18 CSV files organized in long format. Each
document represents different quantitative data tracked by the user's
Fitbit. Every user has a unique ID and the data was tracked by either by
day, hour or minute. Given the small sample size, the data was initially
analyzed using Microsoft Excel. The relations between the tables were
validated and the attributes and length of the survey were summarized
using pivot tables. The Id field was used as the key field to merge the
data sets.

\textbf{Data Privacy}

This Kaggle data set contains personal fitness tracker data from
thirty-three Fitbit users. The users consented to the submission of
personal tracker data and this is made available to the public under a
CC0 license.

\textbf{Data Bias and Limitations}

The sample size of thirty-three individuals is very small and therefore
not representative of the overall population. Also, there is no
demographic information associated with the data. Given that Bellabeat's
main users are women, knowing the gender of the sample would be
advantageous for the analysis and subsequent recommendations. Some
individual logs, such as the weight log, are particularly under sampled
and only contain data from eight users; two-thirds of the entries were
manually entered. Additionally, many logs contain null values. The data
is eight years old and outdated. It is, however, cited many times on
Kaggle and updated frequently.

\textbf{Additional Data Sets}

Given the small sample size of the data set an additional data set could
be used to increase the confidence level, leading to more robust
conclusions. Another approach would be to use a data set that considers
individuals over an extended period of time. One such data set comes
from the Mi Band fitness tracker data. It contains data relating to
steps and sleep for one individual from April 2016 to July 2022
collected from the Mi Band.

\emph{Process}

I chose RStudio to clean and prepare my data as it can handle vast
amount of dataset and is versitile for Data sharing in form of Markdowns
which will come handy in Share phase. Also It will help me document each
step of the process when I clean my data.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#First import some packages}

\FunctionTok{library}\NormalTok{(tidyverse) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'tidyverse' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'tibble' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'tidyr' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'readr' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'purrr' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'dplyr' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'forcats' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'lubridate' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v readr     2.1.5
## v forcats   1.0.0     v stringr   1.5.0
## v ggplot2   3.5.1     v tibble    3.2.1
## v lubridate 1.9.3     v tidyr     1.3.1
## v purrr     1.0.1     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the ]8;;http://conflicted.r-lib.org/conflicted package]8;; to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lubridate)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(tidyr)}
\end{Highlighting}
\end{Shaded}

Importing Datasets

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{activity }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"../bellaboom/mturkfitbit\_export\_4.12.16{-}5.12.16/Fitabase Data 4.12.16{-}5.12.16/dailyActivity\_merged.csv"}\NormalTok{)}
\NormalTok{calories }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"../bellaboom/mturkfitbit\_export\_4.12.16{-}5.12.16/Fitabase Data 4.12.16{-}5.12.16/hourlyCalories\_merged.csv"}\NormalTok{)}
\NormalTok{intensities }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"../bellaboom/mturkfitbit\_export\_4.12.16{-}5.12.16/Fitabase Data 4.12.16{-}5.12.16/hourlyIntensities\_merged.csv"}\NormalTok{)}
\NormalTok{sleep }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"../bellaboom/mturkfitbit\_export\_4.12.16{-}5.12.16/Fitabase Data 4.12.16{-}5.12.16/sleepDay\_merged.csv"}\NormalTok{)}
\NormalTok{weight }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"../bellaboom/mturkfitbit\_export\_4.12.16{-}5.12.16/Fitabase Data 4.12.16{-}5.12.16/weightLogInfo\_merged.csv"}\NormalTok{)}
\NormalTok{steps }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"../bellaboom/mturkfitbit\_export\_4.12.16{-}5.12.16/Fitabase Data 4.12.16{-}5.12.16/dailySteps\_merged.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 940 Columns: 3
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr (1): ActivityDay
## dbl (2): Id, StepTotal
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{verbatim}
## # A tibble: 10 x 3
##            Id ActivityDay StepTotal
##         <dbl> <chr>           <dbl>
##  1 1503960366 4/12/2016       13162
##  2 1503960366 4/13/2016       10735
##  3 1503960366 4/14/2016       10460
##  4 1503960366 4/15/2016        9762
##  5 1503960366 4/16/2016       12669
##  6 1503960366 4/17/2016        9705
##  7 1503960366 4/18/2016       13019
##  8 1503960366 4/19/2016       15506
##  9 1503960366 4/20/2016       10544
## 10 1503960366 4/21/2016        9819
\end{verbatim}

Fixing timestamps

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Intensity}
\NormalTok{intensities}\SpecialCharTok{$}\NormalTok{ActivityHour }\OtherTok{=} \FunctionTok{as.POSIXct}\NormalTok{(intensities}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format =}\StringTok{"\%m/\%d/\%Y \%I:\%M:\%S \%p"}\NormalTok{, }\AttributeTok{tz=}\FunctionTok{Sys.timezone}\NormalTok{())}
\NormalTok{intensities}\SpecialCharTok{$}\NormalTok{time }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(intensities}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format =} \StringTok{"\%H:\%M:\%S"}\NormalTok{)}
\NormalTok{intensities}\SpecialCharTok{$}\NormalTok{date }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(intensities}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%y"}\NormalTok{)}
\CommentTok{\# calories}
\NormalTok{calories}\SpecialCharTok{$}\NormalTok{ActivityHour}\OtherTok{=}\FunctionTok{as.POSIXct}\NormalTok{(calories}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format=}\StringTok{"\%m/\%d/\%Y \%I:\%M:\%S \%p"}\NormalTok{, }\AttributeTok{tz=}\FunctionTok{Sys.timezone}\NormalTok{())}
\NormalTok{calories}\SpecialCharTok{$}\NormalTok{time }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(calories}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format =} \StringTok{"\%H:\%M:\%S"}\NormalTok{)}
\NormalTok{calories}\SpecialCharTok{$}\NormalTok{date }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(calories}\SpecialCharTok{$}\NormalTok{ActivityHour, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%y"}\NormalTok{)}
\CommentTok{\# activity}
\NormalTok{activity}\SpecialCharTok{$}\NormalTok{ActivityDate}\OtherTok{=}\FunctionTok{as.POSIXct}\NormalTok{(activity}\SpecialCharTok{$}\NormalTok{ActivityDate, }\AttributeTok{format=}\StringTok{"\%m/\%d/\%Y"}\NormalTok{, }\AttributeTok{tz=}\FunctionTok{Sys.timezone}\NormalTok{())}
\NormalTok{activity}\SpecialCharTok{$}\NormalTok{date }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(activity}\SpecialCharTok{$}\NormalTok{ActivityDate, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%y"}\NormalTok{)}
\CommentTok{\# sleep}
\NormalTok{sleep}\SpecialCharTok{$}\NormalTok{SleepDay}\OtherTok{=}\FunctionTok{as.POSIXct}\NormalTok{(sleep}\SpecialCharTok{$}\NormalTok{SleepDay, }\AttributeTok{format=}\StringTok{"\%m/\%d/\%Y \%I:\%M:\%S \%p"}\NormalTok{, }\AttributeTok{tz=}\FunctionTok{Sys.timezone}\NormalTok{())}
\NormalTok{sleep}\SpecialCharTok{$}\NormalTok{date }\OtherTok{\textless{}{-}} \FunctionTok{format}\NormalTok{(sleep}\SpecialCharTok{$}\NormalTok{SleepDay, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%y"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\textbf{Data Exploration}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(activity}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(calories}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(intensities}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(sleep}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 24
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(weight}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{n\_distinct}\NormalTok{(steps}\SpecialCharTok{$}\NormalTok{Id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33
\end{verbatim}

There are very 33 different individual's data is present. The sleep data
only has 24 individuals. However Weight has only 8 individuals which is
not enough data to make any solid conclusion. Lets Explore more each
dataset

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Data cleaning {-} checking for duplicate entries}

\FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(activity))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(steps))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(sleep))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(intensities))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(steps))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Data cleaning {-} remove duplicates and drop rows with missing values in any columns}



\NormalTok{sleep }\OtherTok{\textless{}{-}}\NormalTok{ sleep }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{distinct}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{()}

\CommentTok{\#verify missing data}
\FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(sleep))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\emph{Analyse}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Activity summary of sedentary time}
\NormalTok{activity }\SpecialCharTok{\%\textgreater{}\%}  
  \FunctionTok{select}\NormalTok{(TotalSteps,}
\NormalTok{         TotalDistance,}
\NormalTok{         SedentaryMinutes, Calories) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    TotalSteps    TotalDistance    SedentaryMinutes    Calories   
##  Min.   :    0   Min.   : 0.000   Min.   :   0.0   Min.   :   0  
##  1st Qu.: 3790   1st Qu.: 2.620   1st Qu.: 729.8   1st Qu.:1828  
##  Median : 7406   Median : 5.245   Median :1057.5   Median :2134  
##  Mean   : 7638   Mean   : 5.490   Mean   : 991.2   Mean   :2304  
##  3rd Qu.:10727   3rd Qu.: 7.713   3rd Qu.:1229.5   3rd Qu.:2793  
##  Max.   :36019   Max.   :28.030   Max.   :1440.0   Max.   :4900
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Acrivity summary of active time}
\NormalTok{activity }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(VeryActiveMinutes, FairlyActiveMinutes, LightlyActiveMinutes) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  VeryActiveMinutes FairlyActiveMinutes LightlyActiveMinutes
##  Min.   :  0.00    Min.   :  0.00      Min.   :  0.0       
##  1st Qu.:  0.00    1st Qu.:  0.00      1st Qu.:127.0       
##  Median :  4.00    Median :  6.00      Median :199.0       
##  Mean   : 21.16    Mean   : 13.56      Mean   :192.8       
##  3rd Qu.: 32.00    3rd Qu.: 19.00      3rd Qu.:264.0       
##  Max.   :210.00    Max.   :143.00      Max.   :518.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Calories}
\FunctionTok{summary}\NormalTok{(calories) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        Id             ActivityHour                       Calories     
##  Min.   :1.504e+09   Min.   :2016-04-12 00:00:00.00   Min.   : 42.00  
##  1st Qu.:2.320e+09   1st Qu.:2016-04-19 01:00:00.00   1st Qu.: 63.00  
##  Median :4.445e+09   Median :2016-04-26 06:00:00.00   Median : 83.00  
##  Mean   :4.848e+09   Mean   :2016-04-26 11:46:42.58   Mean   : 97.39  
##  3rd Qu.:6.962e+09   3rd Qu.:2016-05-03 19:00:00.00   3rd Qu.:108.00  
##  Max.   :8.878e+09   Max.   :2016-05-12 15:00:00.00   Max.   :948.00  
##      time               date          
##  Length:22099       Length:22099      
##  Class :character   Class :character  
##  Mode  :character   Mode  :character  
##                                       
##                                       
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# sleep}
\NormalTok{sleep }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(TotalSleepRecords, TotalMinutesAsleep, TotalTimeInBed) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  TotalSleepRecords TotalMinutesAsleep TotalTimeInBed 
##  Min.   :1.00      Min.   : 58.0      Min.   : 61.0  
##  1st Qu.:1.00      1st Qu.:361.0      1st Qu.:403.8  
##  Median :1.00      Median :432.5      Median :463.0  
##  Mean   :1.12      Mean   :419.2      Mean   :458.5  
##  3rd Qu.:1.00      3rd Qu.:490.0      3rd Qu.:526.0  
##  Max.   :3.00      Max.   :796.0      Max.   :961.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# weight}
\NormalTok{weight }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(WeightKg, BMI) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     WeightKg           BMI       
##  Min.   : 52.60   Min.   :21.45  
##  1st Qu.: 61.40   1st Qu.:23.96  
##  Median : 62.50   Median :24.39  
##  Mean   : 72.04   Mean   :25.19  
##  3rd Qu.: 85.05   3rd Qu.:25.56  
##  Max.   :133.50   Max.   :47.54
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#steps}
  \FunctionTok{summary}\NormalTok{(steps)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        Id            ActivityDay          StepTotal    
##  Min.   :1.504e+09   Length:940         Min.   :    0  
##  1st Qu.:2.320e+09   Class :character   1st Qu.: 3790  
##  Median :4.445e+09   Mode  :character   Median : 7406  
##  Mean   :4.855e+09                      Mean   : 7638  
##  3rd Qu.:6.962e+09                      3rd Qu.:10727  
##  Max.   :8.878e+09                      Max.   :36019
\end{verbatim}

\textbf{Few intresting discoveries} -Average Step count is 7638 per day.
The Centers for Disease Control and Prevention (CDC) recommends walking
at least 10,000 steps per day. -Average Sedentary time is 991 minutes
which is 16 hours/day. Which is not ideal, users must be made aware of
excercising. -There are average of 1 sleeping session with 6.8 hours of
asleep time.However, avg time in bed is 7.6 hours, some people might
have difficulties fall asleep or due to some other reasons.We can send
notifications to users to sleep in that avg 0.8 hours (58 minutes of
unsleepyness) -People in majority are lightly active.

\textbf{Merging Data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{merged\_data }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(sleep, activity, }\AttributeTok{by=}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Id\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}date\textquotesingle{}}\NormalTok{))}
\FunctionTok{head}\NormalTok{(merged\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           Id     date   SleepDay TotalSleepRecords TotalMinutesAsleep
## 1 1503960366 04/12/16 2016-04-12                 1                327
## 2 1503960366 04/13/16 2016-04-13                 2                384
## 3 1503960366 04/15/16 2016-04-15                 1                412
## 4 1503960366 04/16/16 2016-04-16                 2                340
## 5 1503960366 04/17/16 2016-04-17                 1                700
## 6 1503960366 04/19/16 2016-04-19                 1                304
##   TotalTimeInBed ActivityDate TotalSteps TotalDistance TrackerDistance
## 1            346   2016-04-12      13162          8.50            8.50
## 2            407   2016-04-13      10735          6.97            6.97
## 3            442   2016-04-15       9762          6.28            6.28
## 4            367   2016-04-16      12669          8.16            8.16
## 5            712   2016-04-17       9705          6.48            6.48
## 6            320   2016-04-19      15506          9.88            9.88
##   LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
## 1                        0               1.88                     0.55
## 2                        0               1.57                     0.69
## 3                        0               2.14                     1.26
## 4                        0               2.71                     0.41
## 5                        0               3.19                     0.78
## 6                        0               3.53                     1.32
##   LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
## 1                6.06                       0                25
## 2                4.71                       0                21
## 3                2.83                       0                29
## 4                5.04                       0                36
## 5                2.51                       0                38
## 6                5.03                       0                50
##   FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
## 1                  13                  328              728     1985
## 2                  19                  217              776     1797
## 3                  34                  209              726     1745
## 4                  10                  221              773     1863
## 5                  20                  164              539     1728
## 6                  31                  264              775     2035
\end{verbatim}

\emph{Share \& Act} Lets Plot some Relationships

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Analysis {-} relationship between steps taken in a day and sedentary minutes}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{merged\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{TotalSteps, }\AttributeTok{y=}\NormalTok{SedentaryMinutes))}\SpecialCharTok{+} \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
          \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Daily Steps vs Sedentary Time"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rnotebook_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Relation between TimeAsleep vs TimeinBed}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{merged\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{TotalMinutesAsleep, }\AttributeTok{y=}\NormalTok{SedentaryMinutes))}\SpecialCharTok{+}\FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
          \FunctionTok{geom\_smooth}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Time Asleep vs Time in Bed"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
\end{verbatim}

\includegraphics{Rnotebook_files/figure-latex/unnamed-chunk-10-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Realtion in steps and claories burned}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ merged\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Calories, }\AttributeTok{y=}\NormalTok{TotalSteps, }\AttributeTok{group=}\NormalTok{date))}\SpecialCharTok{+}\FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=} \StringTok{"Steps vs Calories burned"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rnotebook_files/figure-latex/unnamed-chunk-10-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Intentensity breakdown by time}
\NormalTok{int\_new }\OtherTok{\textless{}{-}}\NormalTok{ intensities }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(time) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_total\_int =} \FunctionTok{mean}\NormalTok{(TotalIntensity))}

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{int\_new, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{time, }\AttributeTok{y=}\NormalTok{mean\_total\_int)) }\SpecialCharTok{+} \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{fill=}\StringTok{\textquotesingle{}green\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Average Total Intensity vs. Time"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rnotebook_files/figure-latex/unnamed-chunk-10-4.pdf}

Observations: -There is no relation between Daily steps to sedentary
time. -however, Time asleep decreases with More sedentary minutes. We
can alert users to be more active and reduce their sedentary minutes in
order to improve their sleep. -There is relation between Total steps and
Calories burned but not strong. There might be other activities that
might be accountable for calories burned. -The Intensity between 5 pm to
7 pm are highest.This also some of the busiest times people hit the Gym.
We can remind bellabeat app users to workout. \textbf{\emph{Keep in mind
that we need to support this insights with more data, because
correlation between some data doesn't mean causation.}}

\end{document}
